Generate members.xlsx and responses.xlsx files
Aalto-Salsa-Society/SalsaRaffle pull request #22
Opened 2024-10-26 21:38 UTC by jellyyams

Created script for generating fake member and google form response data. Run script with "uv run datagen.py" in the data dir. 

I'm not familiar with polars and typing so there's definitely cleaner/better ways to write this script. 

I was able to run the raffle script on the excel sheets that were generated.

2024-10-27 08:21 UTC, mennohofste requested changes
Looks good!

I added some small remarks to improve maintainability in the future.

It would be good to run `ruff` formatter and linter on this. This helps a lot with keeping the style uniform.

```bash
uv run ruff format
uv run ruff check
```

The same holds for the type checker, though, if you are unfamiliar, I can give some simple suggestions. It should be very easy in this case.

2024-10-27 08:21 UTC, mennohofste commented on data/datagen.py
> +    class_pref = [str(choice(CLASSES, p=CLASS_DIST)) for x in range(NUM_MEMBERS)]
This is a minor remark, but using `numpy.random.choice` might be a bit overkill here. If possible, we should avoid using numpy, since we are using polars instead.

You could use the standard library instead
```python
import random

class_pref = random.choices(CLASSES, weights=CLASS_DIST, k=NUM_MEMBERS)
```
The same could be done for the other usages of `choice`.

2024-10-27 08:21 UTC, mennohofste commented on data/datagen.py
> +CLASS_DIST = [0.3, 0.15, 0.15, 0.1, 0.2, 0.1] #first choice class preference distribution
Maybe putting these close to the classes, roles and second pref options might be easier to see in 1 look.

2024-10-27 08:21 UTC, mennohofste commented on data/datagen.py
> +        "Full name (first and last name)" : names,
Since you are generating a `DataFrame` with the exact columns that are used in the registration, it would be best if you reuse the names there to have them always in sync.

In this case, the registration files' columns are found in `REGISTRATION_COLUMNS`, so reusing those in some way would be beneficial if names change in the future.

2024-10-27 08:59 UTC, mennohofste commented on data/datagen.py
> +#type: ignore
If you are unfamiliar with how to type, I can add them later as well.

Most of the types are very simple here. 

```python
def gen_data():
```

becomes
```python
def gen_data() -> pl.DataFrame:
```

and taking an argument is as follows:
```python
def write_members_file(df):
```
to
```python
def write_members_file(df: pl.DataFrame):
```

2024-10-31 16:33 UTC, mennohofste requested changes
Great improvements. If you make these last changes including the Ruff issues, I think it can be merged. The last little things I can clean up in a formatting commit.

2024-10-31 16:33 UTC, mennohofste commented on scripts/datagen.py
> +OUTPUT_DIR = "data/fakeinput/"
Could you make the outputs `Path`, such as done in `settings.py`? That makes it easier later. Could you also create it in a `generated_input` or similar, so it is easier to see that this script is related?

2024-10-31 16:33 UTC, mennohofste commented on scripts/datagen.py
> +]  # first choice class preference distribution
I would generally put comments above the variable they are about instead of below.

2024-10-31 16:33 UTC, mennohofste commented on src/salsaraffle/settings.py
> +INPUT_DIR: Final = Path("data") / "fakeinput"
Do not commit this change. The input dir should stay the same.

2024-11-01 16:38 UTC, jellyyams commented
I addressed all the ruff errors except for those saying I shouldn't use pseudo-random generators for cryptographic purposes

2024-11-06 18:27 UTC, mennohofste approved these changes

2024-11-06 18:28 UTC, merged